In [3]:
pip install numpy --upgrade --quiet

Note: you may need to restart the kernel to use updated packages.


In [1]:
import numpy as np

In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

In [9]:
np.dot(arr1, arr2)

32

In [10]:
(arr1 * arr2).sum()

32

In [19]:
climate_data = np.array([[73, 67, 43],
                         [91, 88, 64],
                         [87, 134, 58]])

In [13]:
climate_data.dtype

dtype('int32')

In [14]:
arr3 = np.array([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.5]]])

In [15]:
arr3.dtype

dtype('float64')

In [20]:
np.matmul(arr2,climate_data)


array([1269, 1512,  840])

In [22]:
arr2 @ climate_data


array([1269, 1512,  840])

In [26]:
import urllib.request

urllib.request.urlretrieve(
    'https://hub.jovian.ml/wp-content/uploads/2020/08/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x1fbf98d7a20>)

In [27]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)


In [44]:
climate_data.shape

(10000, 3)

In [31]:
weights = np.array([0.3, 0.2, 0.5])

In [34]:
yeild= np.matmul(climate_data,weights)

In [36]:
yeild.shape

(10000,)

In [40]:
climate_results = np.concatenate((climate_data,yeild.reshape(10000,1)),axis=1)

In [42]:
climate_results


array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [43]:
climate_results.shape

(10000, 4)